### ISSUE TITLE
Revisar F5 despues de logearse, se pierde el estado

### ISSUE THREAD

**Issue by santiagotrini** [paiput/mecu#1]
Revisar porque tira error al refrescar en la pagina de cuenta

**Comment by santiagotrini** [comment]
Bueno, encontre una solucion. No se si es la mejor pero funciona. Inspirado en esta pregunta https://stackoverflow.com/questions/65443984/react-usecontext-on-page-refresh-loses-data

Cuando en tu componente `Account` apretas F5 se dispara el rerender. Pero la operacion de obtener el valor de `user` de `UserContext` es asincrona, entonces cuando va a leer valores como `user.surname` o el que sea esta leyendo `null.surname` que obviamente tira error. Pero en realidad el contexto funciona, solo hay que darle un cachito de tiempo a que actualice. Por ejemplo para solucionar el problema en Account podes usar `&&` antes de renderizar para chequear que no sea null. Te copio la version de `Account.jsx` que tengo aca y funciona (solo el return).

```js
  return (
    <div className="user-container">
      <div className="user-container__child user__profile">
        <div className="user__img-container">
          <img
            src={`https://avatars.dicebear.com/api/initials/${user && user.name}-${user && user.surname}.svg`}
            onError={(e) => {e.target.onerror = null; e.target.src=`${userImg}`}}
            alt="perfil de usuario"
            className="user__img"
          />
        </div>
        <h2>{user && user.username}</h2>
        <h3>{user && user.name} {user && user.surname}</h3>
      </div>
      <div className="user-container__child user__balance-container">
        <h3>Billetera: </h3>
        <h2>${user && handleService.numberWithCommas(user.balance)}</h2>
        <Link to="/account/balance" className="user__link">Cargar dinero</Link>
      </div>
      <div className="user-container__child">
        <Link to="/account/favorites" className="user__link">Favoritos</Link>
      </div>
      <div className="user-container__child user__links">
        <Link to="/account/publishedproducts" className="user__link">Mis publicaciones</Link>
        <Link to="/account/purchasedproducts" className="user__link">Historial de compra</Link>
        <Link to="/account/productssold" className="user__link">Historial de venta</Link>
      </div>
      <div className="user-container__child danger-buttons-container">
        <button className="text-button secondary-danger-button" onClick={handleLogout}>Cerrar sesión</button>
        <button className="text-button primary-danger-button" onClick={handleDeleteAccount}>Borrar cuenta</button>
      </div>
    </div>
  )
```

Fijate que en el componente de Favoritos pasa lo mismo. Fijate que cada vez que leo un valor de `user` antes me fijo que no sea null como en `<h2>${user && handleService.numberWithCommas(user.balance)}</h2>`

**Comment by paiput** [comment]
Gracias.
